# brian's standard Appveyor config for Perl 5 modules
# https://github.com/briandfoy/brians_perl_modules_appveyor_config
# This file is licensed under the Artistic License 2.0

image:
  - Ubuntu

environment:
  PERL5LIB: /home/appveyor/perl5/lib/perl5

platform: x64

branches:
  only:
    - master
    - appveyor

skip_tags: true

install:
  - sh: sudo apt-get install build-essential git libssl-dev
  - sh: sudo apt-get install -y perl
  - sh: export PATH=/home/appveyor/perl5/bin:$PATH
  - perl -v
  - cpan App::cpanminus
  - cpanm --installdeps .

build_script:
  - perl Makefile.PL
  - sh: make test
