os: osx

language: perl

before_install:
    - uname -a
    - perl -v

install:
    -
    - cpan -T . < yes
    - cpan -T Devel::Cover Devel::Cover::Report::Coveralls

script:
    - cover -delete && cover -test

after_success:
    - cover -report coveralls
