# brian's standard Travis CI config for Perl 5 modules
# https://github.com/briandfoy/brians_perl_modules_travis_config
# This file is licensed under the Artistic License 2.0

sudo: false

language: perl

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

# https://github.com/kiwiroy/travis-osx-perl/blob/master/.travis.yml
before_install:
  - |
    if [[ ! -x $HOME/perl5/perlbrew/bin/perlbrew ]]; then
      \curl -L https://install.perlbrew.pl | bash
    fi
  - |
    if [[ -f $HOME/perl5/perlbrew/etc/bashrc ]]; then
      source $HOME/perl5/perlbrew/etc/bashrc
    else
      export PATH=$HOME/perl5/perlbrew/bin:$PATH
    fi
  - perlbrew --quiet install-cpanm --force
  - eval "$(perlbrew env $TRAVIS_PERL_VERSION)"
  - export PATH=${PERLBREW_PATH:-$PERLBREW_ROOT/bin}:$PATH

install:
    - perl -v
    - cpanm --quiet --notest Devel::Cover
    - cpanm --quiet --notest Devel::Cover::Report::Coveralls

script:
    - true

after_success:
    - true
